-- One-time load of current inventory from inventory9_17.pdf.
-- Vendors (growers) ----------------------------------------------------
insert into sr_vendors (name)
values
  ('AGN'),
  ('DAP'),
  ('AGCHIN'),
  ('FRESCOS DON GU'),
  ('FRANCISCO NAVARRO MENDOZA'),
  ('Agricola Los Olivos de Marroquin'),
  ('Purchase Product')
on conflict (name) do nothing;

-- Items -----------------------------------------------------------------
insert into sr_items (name, commodity, variety, label, pack_style, size, qty_per_pallet)
values
  ('Lettuce - Iceberg (FRESCO 24CELLO)', 'Lettuce', 'Iceberg', 'FRESCO', 'Carton', '24CELLO', 40),
  ('Celery - Celery (HB 24)', 'Celery', 'Celery', 'HB', 'Carton', '24', 32),
  ('Bell Pepper - Yellow (HB LGE)', 'Bell Pepper', 'Yellow', 'HB', 'Carton', 'LGE', 56),
  ('Bell Pepper - Yellow (HB MEDCH)', 'Bell Pepper', 'Yellow', 'HB', 'Carton', 'MEDCH', 56),
  ('Bell Pepper - Yellow (HB XLG)', 'Bell Pepper', 'Yellow', 'HB', 'Carton', 'XLG', 56),
  ('Bell Pepper - Orange (HB LGE)', 'Bell Pepper', 'Orange', 'HB', 'Carton', 'LGE', 56),
  ('Bell Pepper - Orange (HB MEDCH)', 'Bell Pepper', 'Orange', 'HB', 'Carton', 'MEDCH', 56),
  ('Bell Pepper - Orange (HB XLG)', 'Bell Pepper', 'Orange', 'HB', 'Carton', 'XLG', 56),
  ('Bell Pepper - Red (HB LGE)', 'Bell Pepper', 'Red', 'HB', 'Carton', 'LGE', 56),
  ('Bell Pepper - Red (HB MEDCH)', 'Bell Pepper', 'Red', 'HB', 'Carton', 'MEDCH', 56),
  ('Bell Pepper - Red (HB XLG)', 'Bell Pepper', 'Red', 'HB', 'Carton', 'XLG', 56),
  ('Bell Pepper - Mini Sweets (HB YLWBLK)', 'Bell Pepper', 'Mini Sweets', 'HB', 'Carton', 'YLWBLK', 56),
  ('Celery - Celery (GEN 24)', 'Celery', 'Celery', 'GEN', 'Carton', '24', 32),
  ('Celery - Celery (GEN 30)', 'Celery', 'Celery', 'GEN', 'Carton', '30', 32),
  ('Lettuce - Romaine (GEN 24LINER)', 'Lettuce', 'Romaine', 'GEN', 'Carton', '24LINER', 40),
  ('Broccoli - Asian Cut (20# FCR)', 'Broccoli', 'Asian Cut', '20#', 'Carton', 'FCR', 56),
  ('Lettuce - Iceberg (HB 24CELLO)', 'Lettuce', 'Iceberg', 'HB', 'Carton', '24CELLO', 40),
  ('Bell Pepper - Green (GEN MED)', 'Bell Pepper', 'Green', 'GEN', 'Carton', 'MED', 56),
  ('Bell Pepper - Yellow (GEN JBO)', 'Bell Pepper', 'Yellow', 'GEN', 'Carton', 'JBO', 100),
  ('Bell Pepper - Yellow (GEN LGE)', 'Bell Pepper', 'Yellow', 'GEN', 'Carton', 'LGE', 100),
  ('Bell Pepper - Red (GEN LGE)', 'Bell Pepper', 'Red', 'GEN', 'Carton', 'LGE', 100),
  ('Cucumber - American (GEN LG)', 'Cucumber', 'American', 'GEN', 'Carton', 'LG', 42),
  ('Broccoli - Asian Cut (20# FCG)', 'Broccoli', 'Asian Cut', '20#', 'Carton', 'FCG', 56),
  ('Carrots - Polish (GEN JBO)', 'Carrots', 'Polish', 'GEN', 'Sack', 'JBO', 50),
  ('Carrots - Polish (GEN PROC)', 'Carrots', 'Polish', 'GEN', 'Sack', 'PROC', 50),
  ('Carrots - Polish (GEN SJBO)', 'Carrots', 'Polish', 'GEN', 'Sack', 'SJBO', 50),
  ('Cauliflower - Cauliflower (GEN 12CT)', 'Cauliflower', 'Cauliflower', 'GEN', 'Carton', '12CT', 48),
  ('Lettuce - Iceberg (GEN 24CELLO)', 'Lettuce', 'Iceberg', 'GEN', 'Carton', '24CELLO', 40),
  ('Lettuce - Green Leaf (GEN 24LINER)', 'Lettuce', 'Green Leaf', 'GEN', 'Carton', '24LINER', 40)
on conflict (name) do nothing;

-- Inventory lots ----------------------------------------------------------
insert into sr_inventory_lots (item_id, vendor_id, lot_number, received_date, qty_on_hand, warehouse, status)
values
  ((select id from sr_items where name = 'Lettuce - Iceberg (FRESCO 24CELLO)'), (select id from sr_vendors where name = 'AGN'), 'G046.CA-6573', '2026-09-17', 39, '01', 'available'),
  ((select id from sr_items where name = 'Celery - Celery (HB 24)'), (select id from sr_vendors where name = 'DAP'), 'G055.6HSB-321', '2026-09-12', 192, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Yellow (HB LGE)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-210', '2026-09-11', 133, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Yellow (HB LGE)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-211', '2026-09-17', 112, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Yellow (HB MEDCH)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-211', '2026-09-17', 112, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Yellow (HB XLG)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-210', '2026-09-11', 29, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Yellow (HB XLG)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-211', '2026-09-17', 112, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Orange (HB LGE)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-209', '2026-09-09', 108, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Orange (HB LGE)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-210', '2026-09-11', 280, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Orange (HB LGE)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-211', '2026-09-17', 56, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Orange (HB MEDCH)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-209', '2026-09-09', 36, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Orange (HB MEDCH)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-210', '2026-09-11', 48, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Orange (HB MEDCH)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-211', '2026-09-17', 143, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Orange (HB XLG)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-209', '2026-09-09', 96, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Orange (HB XLG)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-211', '2026-09-17', 112, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Red (HB LGE)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-210', '2026-09-11', 451, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Red (HB LGE)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-211', '2026-09-17', 448, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Red (HB MEDCH)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-211', '2026-09-17', 392, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Red (HB XLG)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-209', '2026-09-09', 112, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Red (HB XLG)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-210', '2026-09-11', 168, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Red (HB XLG)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-211', '2026-09-17', 168, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Mini Sweets (HB YLWBLK)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-210', '2026-09-11', 21, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Mini Sweets (HB YLWBLK)'), (select id from sr_vendors where name = 'AGCHIN'), 'G072.CHIN-211', '2026-09-17', 23, '01', 'available'),
  ((select id from sr_items where name = 'Celery - Celery (GEN 24)'), (select id from sr_vendors where name = 'FRESCOS DON GU'), 'G089.DGU-10223', '2026-09-14', 448, '01', 'available'),
  ((select id from sr_items where name = 'Celery - Celery (GEN 30)'), (select id from sr_vendors where name = 'FRESCOS DON GU'), 'G089.DGU-10204', '2026-09-16', 192, '01', 'available'),
  ((select id from sr_items where name = 'Lettuce - Romaine (GEN 24LINER)'), (select id from sr_vendors where name = 'FRESCOS DON GU'), 'G089.DGU-10227', '2026-09-15', 40, '01', 'available'),
  ((select id from sr_items where name = 'Broccoli - Asian Cut (20# FCR)'), (select id from sr_vendors where name = 'FRANCISCO NAVARRO MENDOZA'), 'G094.FCON-19', '2026-09-12', 56, '01', 'available'),
  ((select id from sr_items where name = 'Lettuce - Iceberg (HB 24CELLO)'), (select id from sr_vendors where name = 'Agricola Los Olivos de Marroquin'), 'G096.AGOL-01', '2026-09-14', 311, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Green (GEN MED)'), (select id from sr_vendors where name = 'Purchase Product'), '15591', '2026-09-16', 56, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Yellow (GEN JBO)'), (select id from sr_vendors where name = 'Purchase Product'), '15521', '2026-09-04', 23, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Yellow (GEN LGE)'), (select id from sr_vendors where name = 'Purchase Product'), '15545', '2026-09-10', 100, '01', 'available'),
  ((select id from sr_items where name = 'Bell Pepper - Red (GEN LGE)'), (select id from sr_vendors where name = 'Purchase Product'), '15545', '2026-09-10', 200, '01', 'available'),
  ((select id from sr_items where name = 'Cucumber - American (GEN LG)'), (select id from sr_vendors where name = 'Purchase Product'), '15601', '2026-09-17', 42, '01', 'available'),
  ((select id from sr_items where name = 'Broccoli - Asian Cut (20# FCG)'), (select id from sr_vendors where name = 'Purchase Product'), '15594', '2026-09-16', 271, '01', 'available'),
  ((select id from sr_items where name = 'Broccoli - Asian Cut (20# FCR)'), (select id from sr_vendors where name = 'Purchase Product'), '15594', '2026-09-16', 573, '01', 'available'),
  ((select id from sr_items where name = 'Carrots - Polish (GEN JBO)'), (select id from sr_vendors where name = 'Purchase Product'), '15554', '2026-09-10', 300, '01', 'available'),
  ((select id from sr_items where name = 'Carrots - Polish (GEN JBO)'), (select id from sr_vendors where name = 'Purchase Product'), '15567', '2026-09-12', 250, '01', 'available'),
  ((select id from sr_items where name = 'Carrots - Polish (GEN JBO)'), (select id from sr_vendors where name = 'Purchase Product'), '15581', '2026-09-14', 50, '01', 'available'),
  ((select id from sr_items where name = 'Carrots - Polish (GEN JBO)'), (select id from sr_vendors where name = 'Purchase Product'), '15584', '2026-09-15', 50, '01', 'available'),
  ((select id from sr_items where name = 'Carrots - Polish (GEN PROC)'), (select id from sr_vendors where name = 'Purchase Product'), '15585', '2026-09-15', 250, '01', 'available'),
  ((select id from sr_items where name = 'Carrots - Polish (GEN SJBO)'), (select id from sr_vendors where name = 'Purchase Product'), '15510', '2026-09-03', 200, '01', 'available'),
  ((select id from sr_items where name = 'Carrots - Polish (GEN SJBO)'), (select id from sr_vendors where name = 'Purchase Product'), '15516', '2026-09-04', 400, '01', 'available'),
  ((select id from sr_items where name = 'Carrots - Polish (GEN SJBO)'), (select id from sr_vendors where name = 'Purchase Product'), '15554', '2026-09-10', 100, '01', 'available'),
  ((select id from sr_items where name = 'Carrots - Polish (GEN SJBO)'), (select id from sr_vendors where name = 'Purchase Product'), '15584', '2026-09-15', 200, '01', 'available'),
  ((select id from sr_items where name = 'Celery - Celery (GEN 30)'), (select id from sr_vendors where name = 'Purchase Product'), '15595', '2026-09-17', 64, '01', 'available'),
  ((select id from sr_items where name = 'Celery - Celery (GEN 30)'), (select id from sr_vendors where name = 'Purchase Product'), '15595', '2026-09-17', 32, '01', 'available'),
  ((select id from sr_items where name = 'Cauliflower - Cauliflower (GEN 12CT)'), (select id from sr_vendors where name = 'Purchase Product'), '15592', '2026-09-16', 96, '01', 'available'),
  ((select id from sr_items where name = 'Lettuce - Iceberg (GEN 24CELLO)'), (select id from sr_vendors where name = 'Purchase Product'), '15597', '2026-09-16', 80, '01', 'available'),
  ((select id from sr_items where name = 'Lettuce - Romaine (GEN 24LINER)'), (select id from sr_vendors where name = 'Purchase Product'), '15597', '2026-09-16', 40, '01', 'available'),
  ((select id from sr_items where name = 'Lettuce - Romaine (GEN 24LINER)'), (select id from sr_vendors where name = 'Purchase Product'), '15599', '2026-09-17', 160, '01', 'available'),
  ((select id from sr_items where name = 'Lettuce - Green Leaf (GEN 24LINER)'), (select id from sr_vendors where name = 'Purchase Product'), '15597', '2026-09-16', 80, '01', 'available'),
  ((select id from sr_items where name = 'Lettuce - Green Leaf (GEN 24LINER)'), (select id from sr_vendors where name = 'Purchase Product'), '15599', '2026-09-17', 80, '01', 'available');
